DROP SCHEMA IF EXISTS `ls_meals`;
CREATE SCHEMA `ls_meals`;
USE `ls_meals`;

CREATE TABLE IF NOT EXISTS `customer`(
	id BIGINT(20) AUTO_INCREMENT NOT NULL,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	phone VARCHAR(50),
	user_pass VARCHAR(50) NOT NULL,
	
	PRIMARY KEY (id)
) ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `meal`(
	id BIGINT(20) AUTO_INCREMENT NOT NULL,
	name VARCHAR(50) NOT NULL,
	cost NUMERIC(6,2) NOT NULL,
	photo_url VARCHAR(100),
	
	PRIMARY KEY (id)
) ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `rating`(
	id BIGINT(20) AUTO_INCREMENT NOT NULL,
	rating_stars TINYINT,
	comments VARCHAR(100),
	meal_id BIGINT(20) NOT NULL,
	
	PRIMARY KEY (id),
	KEY `fk_meal` (`meal_id`),
	CONSTRAINT `fk_meal` FOREIGN KEY (`meal_id`) REFERENCES `meal` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `delivery`(
	id BIGINT(20) AUTO_INCREMENT NOT NULL,
	date DATETIME,
	rating_stars TINYINT,
	comments VARCHAR(100),
	customer_id BIGINT(20) NOT NULL,
	
	PRIMARY KEY (id),
	KEY `fk_customer` (`customer_id`),
	CONSTRAINT `fk_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `delivery_meal` (
	id BIGINT(20) AUTO_INCREMENT NOT NULL,
	delivery_id BIGINT(20) NOT NULL,
	meal_id BIGINT(20) NOT NULL,
	
	PRIMARY KEY (id),
	KEY `fk_delivery_meal` (`delivery_id`),
	CONSTRAINT `fk_delivery_meal` FOREIGN KEY (`delivery_id`) REFERENCES `delivery` (`id`),
	KEY `fk_meal_delivery` (`meal_id`),
	CONSTRAINT `fk_meal_delivery` FOREIGN KEY (`meal_id`) REFERENCES `meal` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1;

/* Customers: 100 */
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Hop","Brooks","interdum.Curabitur@tellus.com","(01383) 59591","XTO12UYS");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Holly","Pennington","nec.diam@egestasligulaNullam.co.uk","(018486) 82398","YEW42KUR");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Tana","David","mollis@asollicitudin.edu","0800 858037","IDZ34IIY");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Alexa","Langley","nulla.at@vitaeorci.com","0800 097 0515","CFK48KTZ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Malik","Donaldson","ultrices.a@semmollisdui.edu","07624 789331","IGD13REW");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Ina","Reid","Duis@etmalesuadafames.co.uk","(0151) 773 2045","EVN57PQQ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Ayanna","Holloway","conubia.nostra@aliquet.com","(012239) 91429","GSF03NDV");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Melyssa","Gentry","non.lacinia.at@consectetuercursuset.net","(016977) 2995","TQY48ZNP");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Chloe","Shaffer","Nullam@ligula.co.uk","07624 470017","TIZ12HVB");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Patience","Ferrell","rhoncus.id@nibhvulputate.co.uk","(0121) 646 9746","XAV89GMZ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Bo","Phillips","eleifend.non@vulputatelacus.com","0500 456421","FWX07XLI");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Iola","Murphy","erat.semper@Vivamusmolestie.co.uk","0900 462 0821","XAW54CIC");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Jasper","Ratliff","pellentesque.Sed@tempordiam.com","070 9379 7088","ONH41TUI");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Shad","Soto","ut@ultricesDuis.ca","0851 447 7908","XNB28HTN");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Willow","Robinson","morbi.tristique.senectus@posuereenimnisl.ca","0800 645507","SOS70ODQ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Althea","Livingston","mollis@porttitorinterdum.ca","0800 695662","INB27VVI");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Priscilla","Kim","elit.pellentesque.a@Quisquelibero.org","0500 467535","XRE88DAM");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Hammett","Rios","augue.ut.lacus@nec.net","0845 46 45","HHS28SJJ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Elmo","Miranda","egestas@musDonecdignissim.ca","0344 787 0720","OQU45FSG");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Laurel","Maldonado","velit.dui.semper@eleifend.edu","076 3743 5551","QWG02SAZ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Yoko","Barr","laoreet.lectus.quis@FuscemollisDuis.co.uk","(013464) 85364","DKG15YUM");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Noelle","Raymond","Aliquam.auctor@sempercursus.net","056 0243 9916","NIE95WEV");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Duncan","Gordon","tempus.mauris.erat@placeratorci.net","0985 219 2208","ANW76TVH");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Stuart","Gaines","sem.semper@nuncinterdumfeugiat.edu","0835 504 7010","ILH39CHP");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Ezra","Huffman","Fusce@aliquameros.com","(016977) 7116","BMZ30RRJ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Laurel","Sherman","risus@SuspendissesagittisNullam.com","07211 672307","PSW53NOZ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Logan","Tyson","ut.sem@laciniaSedcongue.ca","056 4469 0149","EWI80LUG");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Ronan","Estes","ut@libero.com","(0119) 160 5318","NPU53TSB");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Lesley","Richmond","urna.et.arcu@ridiculusmusProin.edu","(016977) 1558","MIW73JKH");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Ronan","Mckee","Aliquam.vulputate@elit.org","(01773) 73533","EDE16UFT");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Alexis","Beck","mauris.rhoncus.id@nunc.com","055 1388 6956","VAL71TMP");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Irene","Compton","mi.lacinia.mattis@interdum.net","0334 264 7090","BFU58EYF");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Hiram","Benton","erat.vel.pede@faucibusMorbi.org","0845 46 46","PCU28FJQ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Destiny","Dickson","bibendum@rhoncusNullamvelit.edu","0500 318606","QGT62RAK");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Lev","Mcclure","et@rutrumjusto.org","076 7908 0507","XWN63YNR");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Leroy","Gay","accumsan.neque@quamafelis.com","(016977) 8422","GPA46OAQ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Benjamin","Cohen","augue.ac.ipsum@pharetra.ca","(01044) 314134","LCQ93FUY");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Veda","Dunlap","quis.massa@Duis.ca","055 3836 7483","PJT89WEQ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Clark","Garza","egestas@aliquamarcuAliquam.edu","(011528) 55059","FHZ09RNO");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Ocean","Hayes","facilisis@ligula.edu","07815 790111","BRS92YOJ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Elton","Rivera","porttitor.vulputate@nonfeugiat.com","076 5008 2973","DXJ95WNS");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Fritz","Wallace","luctus.ipsum@sagittis.edu","(016977) 4415","SPS72CIN");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Iola","Hartman","dapibus@ante.org","056 7272 8429","KNG43QWD");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Yael","Hayes","vestibulum.Mauris@nondui.ca","07624 165404","NOD63YQV");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Gail","Berry","dolor.tempus.non@Inat.ca","0800 105326","SSI98EGX");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Trevor","Gardner","eu.sem.Pellentesque@Duis.com","(0101) 747 0802","UCT92YMW");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Xandra","Caldwell","vitae.semper@pede.co.uk","(0117) 940 9846","FJB44EXW");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Neville","Holder","commodo@Aeneangravida.net","076 2126 4724","TNP30JII");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Ryder","Walls","sed@Pellentesque.ca","0849 501 6316","SQE05PRI");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Eve","Dunn","Integer.aliquam.adipiscing@facilisis.ca","070 5730 3626","KLC30MVJ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Shaine","Ellison","arcu.Vestibulum.ante@risusvarius.ca","07698 310668","ZJA59LLG");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Philip","Glenn","et@purus.net","(027) 0321 9497","HQT34SLB");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Susan","Montoya","primis.in@libero.ca","0810 434 9304","XXD91IQE");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Ezra","Macdonald","amet@elit.co.uk","0800 1111","YTR04YXV");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Daria","Church","turpis@malesuada.ca","07678 875060","URK76EDQ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Davis","Herman","vitae.posuere.at@hendreritconsectetuercursus.edu","0927 411 5650","KXB44ZCF");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Barclay","Gregory","non@non.com","0811 407 7432","PMX79AKT");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Channing","Bass","magna.Cras@estacfacilisis.co.uk","0800 1111","RQX87LYP");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Claire","Fletcher","sollicitudin.a@egetvenenatisa.ca","055 7400 0208","JIQ05WJU");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Shelley","Williamson","ornare@utmolestie.org","0845 46 46","HOP53TYM");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Troy","Bernard","neque.non@iaculisodioNam.edu","(01356) 233119","WEW65RXQ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Alyssa","Le","egestas@Quisquepurussapien.org","055 4347 6752","TWT98OKY");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Amy","Velasquez","sit@velitAliquam.net","0800 959892","FSH54ZEQ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Harrison","Cortez","faucibus@quis.org","070 0516 6007","CLG52RBX");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Yoshio","Cooley","penatibus@dolorNullasemper.co.uk","070 7475 2862","HBX66FIV");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Tamekah","Underwood","amet.consectetuer.adipiscing@molestieintempus.edu","0845 46 41","BMS37RSD");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Ori","Johnson","eu.ligula@Nuncullamcorpervelit.edu","0806 516 0669","MJV30EUC");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Bert","Witt","est@idanteNunc.net","(028) 8902 0358","ADM43PCF");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Rebecca","Mooney","diam.Sed@nonlorem.org","(010533) 92132","BAN06TJQ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Rosalyn","Sears","molestie@interdumlibero.com","0800 615 7465","ZGW33YBE");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Calista","Bullock","neque.pellentesque@euturpis.org","0882 630 2032","KDQ46FPB");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Stephen","Case","molestie.pharetra.nibh@penatibusetmagnis.org","(012619) 82545","WER57SBW");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Abbot","Newton","commodo.ipsum@velitCraslorem.org","(0118) 782 5905","DCL50HXX");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Courtney","Nash","auctor@dolorNulla.edu","056 8546 7763","QZB81VBP");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Pascale","Johnson","enim@nec.ca","076 4729 6563","VFJ10MTW");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Vance","Vega","ante@musDonecdignissim.co.uk","0800 684 3704","XFX79VKH");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Courtney","Calderon","libero.Integer.in@elitpretiumet.edu","0835 886 8448","HJK26AQR");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Clementine","Holloway","eget.venenatis@etrutrumnon.ca","07624 866813","HYQ67SRJ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Luke","Valencia","Curabitur.consequat.lectus@euismodindolor.co.uk","07459 138929","HYD62FRQ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Clark","Bradshaw","dictum.augue@metusfacilisislorem.edu","(01553) 78905","TEY81IJY");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Amos","Morgan","at.pretium.aliquet@euismodacfermentum.org","(019476) 14463","DMH53YUA");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Cynthia","Lindsey","mattis@ac.net","0845 46 47","TCB21NAK");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Zenaida","Ortiz","Cum.sociis.natoque@aliquet.co.uk","(0115) 859 9716","DMO00EJI");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Kermit","Chen","penatibus@venenatis.com","(01854) 810495","HMX34QJA");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Dominique","Shaffer","mauris@ornarelibero.com","(020) 7613 5440","MTG59SFN");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Colorado","Thornton","Quisque@etliberoProin.net","(021) 5355 3630","ZIL57HNY");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Colby","Davidson","cursus.Integer.mollis@lobortisquama.co.uk","07780 800131","RWC06CCR");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Hashim","Swanson","felis.ullamcorper@quispede.org","070 9922 7912","GYM18JHD");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Ocean","Donaldson","lorem@Integeraliquam.edu","07624 474168","JLL76PNU");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Graham","Atkinson","non.egestas.a@urnajustofaucibus.net","0937 417 5236","YGE99QVJ");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Levi","Rose","non.sollicitudin@euturpisNulla.edu","070 0155 6991","WVN35SAM");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Keely","Mcclure","sit.amet.luctus@magna.net","0500 383274","RVQ53MXA");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Lilah","Ward","mi@et.net","0350 422 9074","GNE47UAP");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Brenden","Atkinson","lobortis.nisi@scelerisquescelerisque.org","(01112) 03032","QUE39STN");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Hillary","Greer","molestie.dapibus@Aliquameratvolutpat.co.uk","056 4021 4469","UMY08MSO");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Lenore","Hahn","ut.lacus.Nulla@lobortis.com","0800 398 6063","XUT48IHW");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Summer","Bradford","odio.tristique@ametante.edu","07624 249315","OVW84FZF");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Calista","Dunlap","egestas@temporloremeget.co.uk","07169 606093","RVM45BMS");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Nissim","Johnston","Donec@euaugueporttitor.org","0939 262 7578","AKL39UCA");
INSERT INTO `Customer` (`first_name`,`last_name`,`email`,`phone`,`user_pass`) VALUES ("Lane","Sykes","Mauris.vel.turpis@egestasligula.co.uk","0500 884268","HPU31HZO");

/* Meals: 10 */
INSERT INTO `Meal` (`name`,`cost`,`photo_url`) VALUES ("noodles","4.99","assets/images/meals/noodles.jepg");
INSERT INTO `Meal` (`name`,`cost`,`photo_url`) VALUES ("sandwich","6.99","assets/images/meals/sandwich.jepg");
INSERT INTO `Meal` (`name`,`cost`,`photo_url`) VALUES ("stews","13.99","assets/images/meals/stew.jepg");
INSERT INTO `Meal` (`name`,`cost`,`photo_url`) VALUES ("salad","3.99","assets/images/meals/salad.jepg");
INSERT INTO `Meal` (`name`,`cost`,`photo_url`) VALUES ("soups","2.99","assets/images/meals/soup.jepg");
INSERT INTO `Meal` (`name`,`cost`,`photo_url`) VALUES ("salads","9.99","assets/images/meals/noodles.jepg");
INSERT INTO `Meal` (`name`,`cost`,`photo_url`) VALUES ("cereals","1.99","assets/images/meals/cereals.jepg");
INSERT INTO `Meal` (`name`,`cost`,`photo_url`) VALUES ("tortellini","6.99","assets/images/meals/tortellini.jepg");
INSERT INTO `Meal` (`name`,`cost`,`photo_url`) VALUES ("pizza","15.99","assets/images/meals/pizza.jepg");
INSERT INTO `Meal` (`name`,`cost`,`photo_url`) VALUES ("hamburger","12.99","assets/images/meals/hamburger.jepg");

/* Ratings: 40 */
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (4,"Lorem ipsum dolor sit",3);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (5,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",1);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (2,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",4);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (2,"Lorem ipsum dolor sit amet, consectetuer",6);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (1,"Lorem ipsum dolor sit amet, consectetuer adipiscing",7);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (1,"Lorem ipsum dolor",6);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (1,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",9);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (5,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",10);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (1,"Lorem ipsum dolor",9);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (5,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",9);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (4,"Lorem ipsum dolor sit amet,",4);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (2,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",6);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (1,"Lorem ipsum dolor sit",1);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (2,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",9);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (4,"Lorem ipsum dolor sit amet,",7);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (2,"Lorem ipsum dolor sit amet, consectetuer adipiscing",3);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (1,"Lorem ipsum",2);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (5,"Lorem ipsum dolor",4);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (4,"Lorem ipsum dolor sit amet, consectetuer",6);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (2,"Lorem ipsum dolor sit amet, consectetuer",1);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (5,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",2);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (4,"Lorem ipsum dolor",4);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (5,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",6);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (1,"Lorem ipsum dolor sit",3);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (1,"Lorem ipsum dolor sit",8);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (3,"Lorem ipsum dolor sit amet, consectetuer",5);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (3,"Lorem ipsum dolor sit",8);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (2,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",3);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (2,"Lorem",3);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (3,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",6);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (2,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",10);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (5,"Lorem ipsum dolor sit amet, consectetuer adipiscing",1);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (4,"Lorem ipsum",10);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (1,"Lorem ipsum dolor sit amet, consectetuer adipiscing",6);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (2,"Lorem ipsum dolor sit",2);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (4,"Lorem ipsum dolor",9);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (5,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",10);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (5,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",8);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (5,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",7);
INSERT INTO `rating` (`rating_stars`,`comments`,`meal_id`) VALUES (5,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",1);

/* delivery: 200 */
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-08-08 00:40:00",1,"orci. Ut semper pretium",85);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-08-17 04:49:19",3,"enim. Curabitur massa. Vestibulum accumsan neque",65);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-05-07 02:40:59",2,"ante dictum mi, ac mattis velit justo",27);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-11 20:29:07",5,"Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor",2);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-09-20 23:35:17",3,"gravida molestie arcu. Sed",88);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-01-13 14:09:45",5,"sollicitudin adipiscing ligula. Aenean gravida",35);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-06-08 05:28:53",1,"Donec",51);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-02-08 07:19:17",4,"aliquam eros turpis non enim. Mauris quis turpis vitae",53);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-06-01 22:37:13",1,"bibendum fermentum metus. Aenean sed",75);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-08-08 21:59:03",1,"ipsum. Curabitur consequat, lectus",54);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-02-23 11:03:50",1,"Sed dictum. Proin eget odio. Aliquam vulputate",54);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-08-29 18:48:14",5,"odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat",92);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-08-09 20:43:57",1,"et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim",52);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-11-15 03:21:02",1,"Donec",31);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-02 20:26:16",4,"Cras pellentesque. Sed dictum. Proin eget",64);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-08-26 08:06:11",1,"neque sed",100);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-09-04 10:53:13",2,"amet nulla.",7);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-01-01 02:53:12",1,"ante bibendum ullamcorper. Duis cursus, diam at pretium",62);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-12-20 03:35:00",2,"ornare, libero at auctor ullamcorper, nisl arcu iaculis",58);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-05 16:04:21",3,"leo, in lobortis tellus justo sit amet nulla. Donec",90);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-10-08 22:23:34",5,"Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum.",43);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-08-22 00:58:37",1,"semper",64);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-03-28 10:41:05",1,"elementum sem, vitae aliquam eros turpis non enim. Mauris",70);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-05-05 12:55:08",4,"Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit,",49);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-10-16 19:29:44",5,"Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed",87);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-20 22:06:23",4,"nonummy ut, molestie in, tempus",58);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-10-22 01:28:42",1,"Quisque varius. Nam porttitor scelerisque neque.",6);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-06-28 19:56:34",3,"augue ut lacus. Nulla tincidunt, neque vitae",28);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-11-13 16:25:51",3,"Duis mi enim, condimentum eget, volutpat ornare,",68);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-08-23 18:17:59",4,"elementum, lorem ut aliquam iaculis, lacus pede sagittis augue,",79);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-04-19 11:01:34",3,"feugiat nec, diam. Duis mi enim, condimentum eget,",77);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-08-22 04:14:08",2,"elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris",20);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-05-04 06:17:18",3,"erat semper rutrum. Fusce dolor quam, elementum",26);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-05-23 17:58:12",3,"Nunc mauris sapien, cursus in, hendrerit",60);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-26 01:12:53",4,"fringilla. Donec feugiat metus sit amet",92);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-03-05 02:18:14",3,"nulla vulputate",42);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-08-12 11:15:21",3,"lectus ante dictum mi, ac mattis",77);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-07-06 22:08:35",3,"Mauris",38);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-10 00:52:48",2,"eget massa. Suspendisse eleifend. Cras sed leo. Cras",9);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-02-18 11:47:41",4,"nunc nulla vulputate dui, nec tempus mauris",48);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-06-07 21:53:18",1,"cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam",18);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-02-29 14:40:40",2,"metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec",96);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-12-09 16:10:34",2,"adipiscing elit. Aliquam auctor,",32);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-08-30 06:47:40",5,"erat.",11);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-06-25 02:27:14",4,"lobortis augue scelerisque mollis. Phasellus libero mauris,",32);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-05 18:44:07",2,"at risus. Nunc ac sem ut",45);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-26 07:09:45",1,"nisi magna",3);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-03-17 12:42:38",1,"arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras",35);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-11-01 21:24:34",5,"consequat",89);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-02-15 08:05:16",2,"mus. Aenean eget magna. Suspendisse tristique neque venenatis",1);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-11 10:34:04",1,"a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum",70);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-06 14:07:43",3,"ligula consectetuer rhoncus. Nullam velit dui, semper",72);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-11-26 00:09:38",1,"vitae",67);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-12-29 10:29:23",5,"vitae semper egestas, urna justo",46);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-12-10 09:40:03",5,"semper rutrum. Fusce dolor quam, elementum at, egestas a,",100);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-11-25 19:11:22",2,"cubilia Curae; Phasellus ornare. Fusce mollis. Duis",45);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-06-09 06:16:45",4,"vitae semper egestas, urna justo faucibus",39);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-03-18 02:18:45",3,"Curabitur vel lectus.",60);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-19 03:02:14",4,"sit amet, dapibus id, blandit at, nisi. Cum sociis natoque",99);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-11-16 14:04:34",1,"non,",68);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-08-04 16:31:37",1,"luctus. Curabitur egestas",9);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-02-13 03:36:31",3,"Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor",44);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-02-19 19:01:23",3,"et pede. Nunc sed orci lobortis",42);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-01-17 14:32:43",5,"amet, consectetuer adipiscing elit. Curabitur sed tortor.",94);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-05-21 00:01:34",4,"nibh.",47);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-06-07 08:59:53",5,"Etiam laoreet,",2);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-06-18 14:16:54",1,"vel arcu. Curabitur ut odio vel est tempor bibendum.",82);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-10-13 21:52:54",1,"sed, sapien. Nunc pulvinar arcu et pede.",63);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-02-18 23:51:13",5,"tincidunt vehicula risus. Nulla",40);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-09-02 07:44:32",3,"nibh sit amet orci. Ut sagittis lobortis",98);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-04-23 16:48:36",4,"sociis natoque penatibus",14);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-11-22 17:17:14",2,"quam. Pellentesque habitant morbi tristique senectus et netus et",9);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-02-05 14:47:48",1,"in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum",22);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-10-02 21:15:12",1,"Nunc",76);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-05-12 21:08:11",1,"facilisis lorem",99);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-01-14 13:00:13",3,"vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut",13);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-05-20 01:28:44",5,"turpis. In condimentum. Donec at arcu. Vestibulum",10);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-12-09 06:14:57",4,"sodales nisi magna sed",32);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-08-08 00:53:12",5,"ultrices posuere cubilia Curae; Donec tincidunt.",35);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-05-08 07:15:00",2,"odio. Etiam ligula tortor,",95);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-07-01 02:49:39",1,"magna. Duis dignissim tempor arcu.",79);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-05-31 05:41:04",1,"felis. Nulla tempor augue ac ipsum.",91);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-04 22:17:37",3,"ipsum primis in faucibus orci",57);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-11-24 18:10:51",5,"Mauris eu turpis. Nulla aliquet. Proin",64);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-08-02 11:03:29",4,"eu erat semper rutrum. Fusce dolor quam, elementum at,",40);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-07-21 17:59:02",5,"eu augue",6);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-11 01:06:11",2,"fringilla ornare placerat, orci lacus vestibulum lorem,",22);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-03-14 08:34:26",5,"sagittis. Nullam vitae diam. Proin dolor. Nulla",98);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-09-04 22:11:11",3,"interdum. Sed auctor odio a purus. Duis",9);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-05-31 02:02:42",1,"a felis",90);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-12-18 18:14:37",3,"lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit",63);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-09-21 20:22:48",3,"neque sed dictum eleifend, nunc risus varius orci,",10);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-10-10 02:10:37",4,"sem, consequat nec,",73);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-12-16 07:09:59",4,"quis arcu vel",5);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-05-27 14:21:13",4,"ipsum. Curabitur consequat,",7);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-06-13 12:27:06",2,"ipsum non arcu. Vivamus sit amet",2);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-05-10 16:40:25",3,"urna suscipit nonummy. Fusce fermentum fermentum arcu.",14);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-02-27 11:59:22",2,"Praesent",16);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-06-19 08:41:27",2,"Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat",1);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-06-18 15:19:44",3,"magna.",84);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-01-19 12:37:56",2,"et tristique pellentesque, tellus sem mollis dui, in sodales",97);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-03-15 18:02:49",2,"luctus lobortis. Class aptent",83);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-03-12 22:15:37",3,"Cras eget nisi dictum augue malesuada malesuada. Integer",2);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-06-02 00:44:16",1,"lobortis mauris. Suspendisse aliquet molestie",56);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-09-15 12:45:10",3,"egestas a, dui.",25);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-06-11 19:55:23",1,"purus. Nullam scelerisque neque sed sem",59);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-09-21 07:04:37",3,"cursus a, enim. Suspendisse aliquet, sem",95);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-10-10 15:43:45",3,"ornare tortor at risus. Nunc ac sem ut dolor dapibus",57);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-11-19 16:53:06",5,"Duis elementum, dui quis accumsan convallis, ante lectus convallis",2);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-01-03 20:21:28",1,"ipsum. Phasellus",71);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-21 16:48:46",3,"Fusce mi lorem, vehicula et, rutrum eu,",30);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-10-14 09:19:51",2,"id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis",95);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-09-13 16:50:20",1,"vitae dolor. Donec fringilla. Donec feugiat metus",95);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-07-29 14:58:15",3,"primis",20);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-08-15 13:57:32",2,"pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac,",67);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-06-27 10:16:13",1,"risus. Nulla",21);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-07-28 08:13:02",2,"vitae odio sagittis semper. Nam tempor diam dictum",37);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-04-11 04:09:24",5,"nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo",41);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-03-14 20:04:32",2,"nec, mollis",36);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-10-19 06:26:49",5,"dis parturient",13);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-12-17 21:22:18",2,"ridiculus mus. Proin vel arcu eu odio",23);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-15 09:01:36",4,"Nulla eget metus eu erat semper rutrum.",3);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-08-03 15:37:47",1,"senectus",63);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-05-14 06:01:20",3,"nunc. In at pede. Cras vulputate",6);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-08-20 09:23:56",4,"gravida sagittis. Duis gravida. Praesent eu nulla at sem",89);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-10-26 14:58:22",5,"ullamcorper viverra. Maecenas iaculis aliquet diam. Sed",81);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-02-23 09:56:02",4,"sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum",89);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-05-10 15:44:21",2,"aliquet lobortis, nisi nibh",71);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-03-24 14:43:54",3,"Nunc lectus pede, ultrices a, auctor non, feugiat",49);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-27 19:26:59",2,"tempor",90);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-02-13 15:38:12",1,"fringilla. Donec",24);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-02 14:59:43",4,"ornare. In faucibus.",5);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-03-16 09:01:06",5,"faucibus",76);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-16 01:51:45",2,"in magna. Phasellus dolor elit,",24);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-10-10 08:17:21",5,"Nam",73);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-07-29 07:47:29",2,"et, euismod",94);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-07-16 07:39:13",1,"condimentum eget, volutpat",86);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-10-16 15:53:31",1,"hendrerit neque. In ornare sagittis felis. Donec tempor, est ac",10);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-02-22 14:35:03",4,"quis diam. Pellentesque habitant morbi tristique senectus",54);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-03-18 07:30:33",5,"elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",19);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-05-08 05:15:26",4,"elementum, dui quis accumsan convallis,",49);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-08-13 04:09:46",4,"eu enim. Etiam imperdiet dictum",18);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-09-09 03:06:33",5,"non,",60);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-05-24 11:26:31",3,"diam luctus lobortis.",8);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-03-04 00:28:08",4,"nibh",5);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-07-03 04:29:12",2,"varius et, euismod et, commodo at, libero.",83);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-03-03 03:28:20",5,"ullamcorper. Duis cursus, diam at",8);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-10-02 09:48:27",1,"Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis",62);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-11-15 20:01:48",1,"dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent",81);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-12-10 18:19:13",4,"orci tincidunt adipiscing. Mauris molestie",17);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-28 14:31:34",1,"nisl. Maecenas malesuada",90);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-10-01 18:58:13",1,"eu eros. Nam",80);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-05-25 12:09:23",3,"dictum. Phasellus in felis. Nulla tempor",85);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-30 19:04:01",1,"mauris ipsum porta elit, a feugiat tellus lorem",10);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-01 11:37:40",4,"augue.",78);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-05 11:46:56",2,"condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing",57);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-02-02 18:57:23",4,"pede, malesuada vel, venenatis",12);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-05-31 01:47:46",4,"vel nisl. Quisque fringilla euismod enim.",24);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-05-23 06:31:00",2,"interdum ligula eu enim. Etiam imperdiet dictum magna. Ut",46);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-09-13 04:41:09",3,"a neque. Nullam ut nisi",86);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-26 00:38:03",3,"Quisque ornare tortor at risus. Nunc ac sem",43);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-01-26 15:29:17",3,"lectus pede,",79);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-24 13:48:44",3,"Phasellus fermentum convallis ligula. Donec",13);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-06-09 19:53:51",5,"ante blandit viverra.",35);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-06-03 01:06:08",5,"magna tellus faucibus leo, in lobortis tellus justo",76);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-04 23:17:09",1,"gravida mauris ut mi. Duis risus odio, auctor vitae,",40);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-09-02 14:45:48",4,"tellus.",52);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-11-02 07:32:02",1,"orci.",28);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-07-04 06:05:04",3,"erat, eget tincidunt dui augue eu tellus. Phasellus elit",13);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-27 10:14:54",2,"quis,",56);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-07-27 22:19:20",1,"metus. In nec orci. Donec nibh. Quisque",47);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-06-03 10:34:57",4,"vel nisl. Quisque fringilla euismod enim. Etiam",95);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-08-05 03:12:28",5,"turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla",79);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-07-07 04:35:16",1,"risus. Donec egestas. Duis ac arcu.",53);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-10-21 12:31:53",2,"In",98);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-05-02 06:42:37",1,"lacus. Quisque purus",89);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-04-25 11:51:51",2,"dui. Cum sociis natoque penatibus et",73);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-03-02 20:12:27",4,"Donec vitae",68);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-10-12 15:16:47",4,"commodo tincidunt nibh.",73);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-03-10 12:05:59",5,"id risus quis",74);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-08 14:27:21",4,"mi pede, nonummy ut, molestie in, tempus eu, ligula.",72);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-21 12:46:16",5,"magnis dis parturient montes, nascetur ridiculus mus. Donec",78);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-05-02 20:54:30",3,"mi, ac mattis",47);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-10-23 22:26:48",5,"fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula",78);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-11-27 00:12:43",2,"lectus pede, ultrices",20);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-09-16 12:15:29",2,"lorem",57);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-11-24 23:13:47",4,"fames ac turpis",11);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-09-13 12:31:57",1,"sit amet,",39);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-05-09 02:23:50",3,"cursus. Integer mollis. Integer",64);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-07-16 13:10:12",2,"pellentesque. Sed dictum. Proin eget",92);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-01-04 04:34:09",1,"sem magna nec",28);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-08-17 01:37:52",4,"malesuada malesuada. Integer id magna et ipsum",11);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-10-24 13:14:09",3,"sed, hendrerit a, arcu. Sed et libero. Proin mi.",91);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-03-12 04:32:04",3,"ac mattis velit justo nec ante.",46);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-03-21 20:44:03",5,"sed dui. Fusce aliquam, enim nec tempus scelerisque,",4);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-12-14 03:01:46",1,"feugiat metus sit",92);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2021-04-16 18:29:11",2,"urna. Vivamus molestie dapibus",58);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-11-26 16:06:35",2,"hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu",93);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2019-12-16 00:46:20",1,"nec urna et",53);
INSERT INTO `delivery` (`date`,`rating_stars`,`comments`,`customer_id`) VALUES ("2020-09-13 13:31:53",5,"velit egestas lacinia. Sed congue, elit sed",9);

/* delivery_meal: 400 */
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (142,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (193,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (81,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (162,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (112,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (52,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (96,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (127,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (113,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (70,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (95,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (96,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (34,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (161,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (94,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (185,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (47,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (140,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (187,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (15,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (50,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (12,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (128,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (38,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (137,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (186,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (177,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (124,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (191,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (66,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (156,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (191,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (78,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (191,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (11,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (161,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (61,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (59,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (142,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (111,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (48,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (89,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (14,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (43,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (141,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (176,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (133,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (158,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (137,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (129,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (31,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (150,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (183,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (42,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (136,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (191,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (40,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (40,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (7,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (129,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (105,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (97,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (163,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (23,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (151,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (77,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (133,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (172,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (83,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (95,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (173,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (166,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (180,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (27,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (74,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (102,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (23,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (8,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (164,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (187,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (187,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (22,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (85,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (40,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (95,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (196,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (153,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (171,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (132,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (141,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (30,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (154,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (20,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (160,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (113,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (197,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (155,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (127,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (111,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (192,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (163,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (11,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (90,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (85,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (26,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (116,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (37,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (18,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (129,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (21,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (109,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (108,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (150,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (138,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (192,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (36,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (63,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (164,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (79,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (89,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (18,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (49,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (11,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (97,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (92,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (104,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (186,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (129,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (49,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (167,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (141,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (31,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (52,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (145,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (81,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (43,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (65,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (7,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (191,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (149,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (117,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (134,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (72,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (197,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (157,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (100,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (28,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (173,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (144,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (107,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (136,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (110,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (8,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (157,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (173,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (118,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (18,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (142,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (103,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (166,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (37,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (105,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (66,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (180,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (99,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (102,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (41,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (69,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (178,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (166,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (181,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (89,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (22,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (43,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (27,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (47,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (145,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (26,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (111,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (11,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (33,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (176,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (90,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (90,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (121,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (178,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (88,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (132,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (152,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (148,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (140,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (142,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (74,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (114,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (169,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (53,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (142,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (64,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (58,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (47,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (31,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (128,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (115,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (191,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (117,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (121,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (103,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (6,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (105,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (149,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (155,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (80,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (169,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (183,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (168,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (148,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (103,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (109,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (111,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (185,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (166,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (26,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (24,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (8,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (6,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (155,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (84,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (10,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (38,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (14,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (50,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (110,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (27,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (91,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (126,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (137,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (143,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (112,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (87,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (167,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (72,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (144,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (168,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (198,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (182,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (87,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (191,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (4,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (192,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (102,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (126,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (51,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (84,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (192,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (173,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (82,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (18,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (73,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (149,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (159,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (38,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (144,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (64,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (24,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (163,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (157,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (44,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (29,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (2,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (87,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (173,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (27,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (194,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (84,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (109,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (106,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (32,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (15,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (36,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (123,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (91,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (57,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (126,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (11,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (178,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (8,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (164,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (137,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (156,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (84,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (37,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (120,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (27,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (104,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (124,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (52,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (132,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (61,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (69,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (56,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (181,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (152,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (190,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (94,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (22,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (197,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (61,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (105,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (141,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (23,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (47,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (130,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (116,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (40,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (6,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (152,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (174,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (31,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (119,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (55,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (136,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (189,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (183,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (99,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (79,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (107,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (15,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (130,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (147,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (16,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (100,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (143,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (159,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (147,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (121,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (114,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (128,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (181,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (189,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (180,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (172,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (67,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (35,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (67,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (116,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (8,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (86,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (76,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (44,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (4,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (56,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (23,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (157,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (194,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (155,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (26,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (22,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (82,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (110,9);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (172,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (88,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (182,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (174,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (107,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (158,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (24,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (111,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (149,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (167,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (29,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (77,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (189,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (47,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (82,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (75,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (175,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (15,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (104,10);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (71,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (65,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (146,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (159,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (27,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (163,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (84,5);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (77,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (46,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (175,7);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (4,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (95,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (12,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (193,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (57,2);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (165,6);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (161,8);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (155,3);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (18,1);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (73,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (190,4);
INSERT INTO `delivery_meal` (`delivery_id`,`meal_id`) VALUES (25,4);
